name:                advent
version:             0.1.0.0
github:              txsmith/advent-of-code-2017
license:             BSD3
author:              Thomas Smith
copyright:           2017 Thomas Smith

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Advent of Code 2017 (http://adventofcode.com/2017) solutions
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Advent of Code 2017 (http://adventofcode.com/2017) solutions

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  advent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
